version: '3'
services:
  payara-micro-1:
    container_name: payara-micro-1
    image: payara/micro
#    ports:
#      - "8081:8080"
    volumes:
      - "~/payara-micro/applications:/opt/payara/deployments"
  payara-micro-2:
    container_name: payara-micro-2
    image: payara/micro
#    ports:
#      - "8082:8080"
    volumes:
      - "~/payara-micro/applications:/opt/payara/deployments"
  nginx:
    container_name: nginx
    build: ./nginx-docker
    ports:
      - "80:80"
    depends_on:
      - payara-micro-1
      - payara-micro-2